<a href="https://colab.research.google.com/github/livjab/energy-project/blob/master/LJ_project_week_data.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

With the incresed awareness of climate change, and the generally agreed upon fact that carbon emissions are causing the changes we are observing, I wanted to explore some of our alternative options for energy production. My goal is to explore which renewable options are the most feasible based on factors such as cost and geographic location, and then determine if there is enough potential in our renewable sources to produce enough energy to eventually phase out the use of fossil fuels in the United States.

In [0]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

## United States Renewable Energy Technical Potential

https://catalog.data.gov/dataset/united-states-renewable-energy-technical-potential

- Renewable energy technical potential as defined in this report represents the achievable energy generation of a particular technology given system performance, topographic limitations, environmental, and land-use constraints.

- The primary benefit of assessing technical potential is that it establishes an upper-boundary estimate of development potential. It is important to understand that there are multiple types of potential—resource, technical, economic, and market—each seen in Figure 1 (below), with key assumptions.

In [0]:
df = pd.read_csv("https://raw.githubusercontent.com/livjab/energy-project/master/usretechnicalpotential.csv?token=AFRLFL6VDSHXJTBVNOLSIWS4XXZBK")

In [7]:
df.shape

(51, 31)

In [8]:
df.describe()

,urbanUtilityScalePV_GWh,urbanUtilityScalePV_GW,urbanUtilityScalePV_km2,ruralUtilityScalePV_GWh,ruralUtilityScalePV_GW,ruralUtilityScalePV_km2,rooftopPV_GWh,rooftopPV_GW,CSP_GWh,CSP_GW,...,biopowerGaseous_GWh,biopowerGaseous_GW,biopowerGaseous_Tonnes-CH4,geothermalHydrothermal_GWh,geothermalHydrothermal_GW,EGSGeothermal_GWh,EGSGeothermal_GW,hydropower_GWh,hydropower_GW,hydropower_countOfSites
count,51.000000,51.000000,51.000000,5.100000e+01,51.000000,51.000000,49.000000,51.000000,5.100000e+01,51.000000,...,51.000000,51.000000,5.100000e+01,51.000000,51.000000,4.900000e+01,49.000000,51.000000,51.000000,51.000000
mean,43758.235294,23.431373,496.921569,5.502219e+06,2999.019608,62488.843137,16708.387755,12.529412,2.277377e+06,746.215686,...,1735.843137,0.019608,3.694256e+05,5909.333333,0.627451,6.396872e+05,80.571429,5077.039216,0.745098,2512.274510
std,54365.369016,27.735360,577.748348,6.284523e+06,3313.295462,69026.482269,19629.574820,14.584036,4.716721e+06,1520.849201,...,2476.107537,0.140028,5.268432e+05,19616.831126,2.357633,5.403773e+05,68.520374,6834.337527,1.547167,2182.471948
min,8.000000,0.000000,0.000000,0.000000e+00,0.000000,0.000000,1115.000000,1.000000,0.000000e+00,0.000000,...,4.000000,0.000000,9.770000e+02,0.000000,0.000000,6.970000e+02,0.000000,0.000000,0.000000,2.000000
25%,12162.000000,6.000000,134.000000,1.296446e+06,792.000000,16508.000000,5336.000000,3.000000,0.000000e+00,0.000000,...,369.000000,0.000000,7.862050e+04,0.000000,0.000000,3.532060e+05,44.000000,1278.500000,0.000000,1038.000000
50%,30492.000000,16.000000,338.000000,4.876185e+06,2395.000000,49908.000000,12442.000000,10.000000,0.000000e+00,0.000000,...,1063.000000,0.000000,2.261780e+05,0.000000,0.000000,4.959210e+05,62.000000,2818.000000,0.000000,1863.000000
75%,51824.000000,31.000000,659.500000,8.235158e+06,4211.000000,87743.000000,19685.000000,14.000000,2.220892e+06,803.000000,...,2183.500000,0.000000,4.647680e+05,686.500000,0.000000,9.219720e+05,116.000000,4663.500000,1.000000,3127.000000
max,294684.000000,154.000000,3213.000000,3.899358e+07,20411.000000,425230.000000,106411.000000,75.000000,2.278675e+07,7743.000000,...,15510.000000,1.000000,3.300211e+06,130921.000000,16.000000,3.030250e+06,384.000000,30023.000000,6.000000,9692.000000

In [9]:
df.head()

,Unnamed: 0,urbanUtilityScalePV_GWh,urbanUtilityScalePV_GW,urbanUtilityScalePV_km2,ruralUtilityScalePV_GWh,ruralUtilityScalePV_GW,ruralUtilityScalePV_km2,rooftopPV_GWh,rooftopPV_GW,CSP_GWh,...,biopowerGaseous_GWh,biopowerGaseous_GW,biopowerGaseous_Tonnes-CH4,geothermalHydrothermal_GWh,geothermalHydrothermal_GW,EGSGeothermal_GWh,EGSGeothermal_GW,hydropower_GWh,hydropower_GW,hydropower_countOfSites
0,Alabama,35850,20,426,3706838,2114,44058,15475.0,12,0,...,1533,0,326186,0,0,535489.0,67.0,4102,0,2435
1,Alaska,166,0,2,8282976,9005,187608,NaN,1,0,...,61,0,13156,15437,1,NaN,NaN,23675,5,3053
2,Arizona,121305,52,1096,11867693,5147,107230,22736.0,14,12544333,...,837,0,178188,8329,1,1239147.0,157.0,1303,0,1958
3,Arkansas,28960,15,332,4986388,2747,57239,8484.0,6,0,...,1063,0,226178,0,0,628621.0,79.0,6093,1,3268
4,California,246008,111,2320,8855917,4010,83549,106411.0,75,8490916,...,15510,1,3300211,130921,16,1344179.0,170.0,30023,6,9692

## Explore dataset with renewable vs fossil fuel production

In [11]:

df1 = pd.read_csv("https://raw.githubusercontent.com/livjab/energy-project/master/MER_T07_02A.csv?token=AFRLFLYDWFBTKFVOSRC6DGK4XXZOA")

df1.head()

,MSN,YYYYMM,Value,Column_Order,Description,Unit
0,CLETPUS,194913,135451.32,1,"Electricity Net Generation From Coal, All Sectors",Million Kilowatthours
1,CLETPUS,195013,154519.994,1,"Electricity Net Generation From Coal, All Sectors",Million Kilowatthours
2,CLETPUS,195113,185203.657,1,"Electricity Net Generation From Coal, All Sectors",Million Kilowatthours
3,CLETPUS,195213,195436.666,1,"Electricity Net Generation From Coal, All Sectors",Million Kilowatthours
4,CLETPUS,195313,218846.325,1,"Electricity Net Generation From Coal, All Sectors",Million Kilowatthours

In [13]:
# drop first column because we have that info elsewhere

df1 = df1.drop(columns=["MSN"])
df1.shape

(8086, 5)

In [0]:
 # only going to keep the rows with 13th month because it is total for that year
  
 # change dtype to string so I can filter using endswith()
  
df1["YYYYMM"] = df1["YYYYMM"].astype('str')

In [15]:
# filter for values ending in "13"

df1 = df1[df1["YYYYMM"].str.endswith("13")]
df1.tail()

,YYYYMM,Value,Column_Order,Description,Unit
8033,201413,4093606.006,13,Electricity Net Generation Total (including fr...,Million Kilowatthours
8046,201513,4077600.939,13,Electricity Net Generation Total (including fr...,Million Kilowatthours
8059,201613,4076674.984,13,Electricity Net Generation Total (including fr...,Million Kilowatthours
8072,201713,4034268.432,13,Electricity Net Generation Total (including fr...,Million Kilowatthours
8085,201813,4177809.699,13,Electricity Net Generation Total (including fr...,Million Kilowatthours

In [0]:
# change dtype back to int so i can do math

df1["YYYYMM"] = df1["YYYYMM"].astype("int64")

In [20]:
df1["Year"] = (df1["YYYYMM"] - 13) / 100
df1.head()

,YYYYMM,Value,Column_Order,Description,Unit,Year
0,194913,135451.32,1,"Electricity Net Generation From Coal, All Sectors",Million Kilowatthours,1949.0
1,195013,154519.994,1,"Electricity Net Generation From Coal, All Sectors",Million Kilowatthours,1950.0
2,195113,185203.657,1,"Electricity Net Generation From Coal, All Sectors",Million Kilowatthours,1951.0
3,195213,195436.666,1,"Electricity Net Generation From Coal, All Sectors",Million Kilowatthours,1952.0
4,195313,218846.325,1,"Electricity Net Generation From Coal, All Sectors",Million Kilowatthours,1953.0

In [21]:
#drop YYYYMM column and reorder remaining columns

df1 = df1.drop(columns=["YYYYMM"])
df1 = df1[['Year', 'Value', 'Column_Order', 'Description', 'Unit']]
df1.head()

,Year,Value,Column_Order,Description,Unit
0,1949.0,135451.32,1,"Electricity Net Generation From Coal, All Sectors",Million Kilowatthours
1,1950.0,154519.994,1,"Electricity Net Generation From Coal, All Sectors",Million Kilowatthours
2,1951.0,185203.657,1,"Electricity Net Generation From Coal, All Sectors",Million Kilowatthours
3,1952.0,195436.666,1,"Electricity Net Generation From Coal, All Sectors",Million Kilowatthours
4,1953.0,218846.325,1,"Electricity Net Generation From Coal, All Sectors",Million Kilowatthours

In [22]:
# check out Unit column

df1["Unit"].describe()

count                       910
unique                        1
top       Million Kilowatthours
freq                        910
Name: Unit, dtype: object

In [0]:
# remove column and remember to label any plots with 
# "Million Kilowatthours"

df1 = df1.drop(columns=["Unit"])

In [24]:
# check out description column

df1["Description"].unique()

array(['Electricity Net Generation From Coal, All Sectors',
       'Electricity Net Generation From Petroleum, All Sectors',
       'Electricity Net Generation From Natural Gas, All Sectors',
       'Electricity Net Generation From Other Gases, All Sectors',
       'Electricity Net Generation From Nuclear Electric Power, All Sectors',
       'Electricity Net Generation From Hydroelectric Pumped Storage, All Sectors',
       'Electricity Net Generation From Conventional Hydroelectric Power, All Sectors',
       'Electricity Net Generation From Wood, All Sectors',
       'Electricity Net Generation From Waste, All Sectors',
       'Electricity Net Generation From Geothermal, All Sectors',
       'Electricity Net Generation From Solar, All Sectors',
       'Electricity Net Generation From Wind, All Sectors',
       'Electricity Net Generation Total (including from sources not shown), All Sectors'],
      dtype=object)

In [25]:
# pivot the data to create more columns

table = df1.pivot(index="Year", columns="Description", values="Value")
table

Description,"Electricity Net Generation From Coal, All Sectors","Electricity Net Generation From Conventional Hydroelectric Power, All Sectors","Electricity Net Generation From Geothermal, All Sectors","Electricity Net Generation From Hydroelectric Pumped Storage, All Sectors","Electricity Net Generation From Natural Gas, All Sectors","Electricity Net Generation From Nuclear Electric Power, All Sectors","Electricity Net Generation From Other Gases, All Sectors","Electricity Net Generation From Petroleum, All Sectors","Electricity Net Generation From Solar, All Sectors","Electricity Net Generation From Waste, All Sectors","Electricity Net Generation From Wind, All Sectors","Electricity Net Generation From Wood, All Sectors","Electricity Net Generation Total (including from sources not shown), All Sectors"
Year,,,,,,,,,,,,,
1949.0,135451.32,94772.992,Not Available,Not Available,36966.709,0,Not Available,28547.232,Not Available,Not Available,Not Available,386.036,296124.289
1950.0,154519.994,100884.575,Not Available,Not Available,44559.159,0,Not Available,33734.288,Not Available,Not Available,Not Available,389.585,334087.601
1951.0,185203.657,104376.12,Not Available,Not Available,56615.678,0,Not Available,28712.116,Not Available,Not Available,Not Available,390.784,375298.355
1952.0,195436.666,109708.251,Not Available,Not Available,68453.088,0,Not Available,29749.761,Not Available,Not Available,Not Available,481.647,403829.413
1953.0,218846.325,109617.396,Not Available,Not Available,79790.975,0,Not Available,38404.449,Not Available,Not Available,Not Available,389.418,447048.563
1954.0,239145.966,111639.772,Not Available,Not Available,93688.271,0,Not Available,31520.175,Not Available,Not Available,Not Available,263.434,476257.618
1955.0,301362.698,116235.946,Not Available,Not Available,95285.441,0,Not Available,37138.308,Not Available,Not Available,Not Available,276.469,550298.862
1956.0,338503.484,125236.621,Not Available,Not Available,104037.208,0,Not Available,35946.772,Not Available,Not Available,Not Available,151.678,603875.763
1957.0,346386.207,133357.93,Not Available,Not Available,114212.525,9.67,Not Available,40499.357,Not Available,Not Available,Not Available,176.678,634642.367
1958.0,344365.781,143614.545,Not Available,Not Available,119759.302,164.691,Not Available,40371.54,Not Available,Not Available,Not Available,175.003,648450.862
1959.0,378424.21,141154.533,Not Available,Not Available,146619.391,188.101,Not Available,46839.719,Not Available,Not Available,Not Available,152.877,713378.831
1960.0,403067.357,149440.035,33.368,Not Available,157969.787,518.182,Not Available,47986.893,Not Available,Not Available,Not Available,140.166,759155.788
1961.0,421870.669,155536.444,94.021,Not Available,169285.998,1692.149,Not Available,48519.376,Not Available,Not Available,Not Available,125.734,797124.391
1962.0,450249.238,172015.646,100.462,Not Available,184301.293,2269.685,Not Available,48879.536,Not Available,Not Available,Not Available,127.796,857943.656
1963.0,493926.719,168990.14,167.953,Not Available,201602.073,3211.836,Not Available,52001.61,Not Available,Not Available,Not Available,127.94,920028.271
1964.0,526230.019,180301.506,203.791,Not Available,220038.479,3342.743,Not Available,56953.712,Not Available,Not Available,Not Available,148.076,987218.326
1965.0,570925.951,196984.345,189.214,Not Available,221559.434,3656.699,Not Available,64801.224,Not Available,Not Available,Not Available,268.804,1058385.671
1966.0,613474.8,197937.538,187.988,Not Available,251151.562,5519.909,Not Available,78926.172,Not Available,Not Available,Not Available,333.926,1147531.895
1967.0,630483.363,224948.605,316.309,Not Available,264805.785,7655.214,Not Available,89270.724,Not Available,Not Available,Not Available,315.688,1217795.688
1968.0,684904.58,225873.158,435.826,Not Available,304432.723,12528.419,Not Available,104275.833,Not Available,Not Available,Not Available,375.062,1332825.601
1969.0,706001.24,253468.237,614.71,Not Available,333278.945,13927.839,Not Available,137847.152,Not Available,Not Available,Not Available,319.933,1445458.056
1970.0,704394.479,250957.442,525.183,Not Available,372890.063,21804.448,Not Available,184183.402,Not Available,220.45,Not Available,136,1535111.467
1971.0,713102.454,269531.459,547.752,Not Available,374030.784,38104.545,Not Available,220225.423,Not Available,199.869,Not Available,111.33,1615853.616
1972.0,771131.265,275928.828,1452.795,Not Available,375747.796,54091.135,Not Available,274295.961,Not Available,199.774,Not Available,130.859,1752978.413
1973.0,847651.47,275430.574,1965.713,Not Available,340858.192,83479.463,Not Available,314342.926,Not Available,197.89,Not Available,130.403,1864056.632
1974.0,828432.921,304211.805,2452.636,Not Available,320065.088,113975.74,Not Available,300930.537,Not Available,182.154,Not Available,68.523,1870319.404
1975.0,852786.222,303152.673,3246.172,Not Available,299778.408,172505.075,Not Available,289094.9,Not Available,173.568,Not Available,17.551,1920754.569
1976.0,944390.993,286924.238,3616.407,Not Available,294623.911,191103.531,Not Available,319988.136,Not Available,182.078,Not Available,84.386,2040913.681
1977.0,985218.596,223598.687,3582.335,Not Available,305504.859,250883.283,Not Available,358178.822,Not Available,173.271,Not Available,307.634,2127447.488
1978.0,975742.083,283465.224,2977.63,Not Available,305390.836,276403.07,Not Available,365060.441,Not Available,140.434,Not Available,197.193,2209376.911
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1989.0,1583779.139,271976.936,14593.443,Not Available,352628.866,529354.717,7862.418,164358.52,250.601,9162.887,2112.043,27236.668,2967146.087
1990.0,1594011.479,292865.846,15434.271,-3507.741,372765.154,576861.678,10382.83,126460.202,367.087,13260.379,2788.6,32521.889,3037827.337
1991.0,1590622.748,288994.189,15966.444,-4541.435,381553.017,612565.087,11335.593,119751.573,471.765,15664.746,2950.951,33725.358,3073798.885
1992.0,1621206.039,253088.003,16137.962,-4176.582,404074.372,618776.263,13270.237,100154.163,399.64,17816.035,2887.523,36528.662,3083882.204
1993.0,1690070.232,280494.008,16788.565,-4035.572,414926.798,610291.214,12955.798,112788.18,462.452,18333.031,3005.827,37623.407,3197191.096
1994.0,1690693.864,260125.733,15535.453,-3377.825,460218.682,640439.832,13319.051,105900.983,486.622,19128.595,3447.109,37937.364,3247522.388
1995.0,1709426.468,310832.748,13378.258,-2725.131,496057.945,673402.123,13869.951,74554.065,496.821,20404.971,3164.253,36521.082,3353487.362
1996.0,1795195.593,347162.063,14328.684,-3088.078,455055.576,674728.546,14355.813,81411.225,521.205,20911.336,3234.069,36800.31,3444187.621
1997.0,1845015.736,356453.295,14726.102,-4039.905,479398.67,628644.171,13350.634,92554.873,511.168,21709.073,3288.035,36948.441,3492172.283
1998.0,1873515.69,323335.661,14773.918,-4467.28,531257.104,673702.104,13492.23,128800.173,502.473,22447.935,3025.696,36338.384,3620295.498
1999.0,1881087.224,319536.029,14827.013,-6096.899,556396.127,728254.124,14125.592,118060.838,495.082,22572.175,4487.998,37040.734,3694809.81
2000.0,1966264.596,275572.597,14093.158,-5538.86,601038.159,753892.94,13954.758,111220.965,493.375,23131.314,5593.261,37594.866,3802105.043
2001.0,1903955.942,216961.045,13740.501,-8823.445,639129.119,768826.308,9039.473,124880.221,542.755,14548.152,6737.331,35199.905,3736643.649
2002.0,1933130.354,264328.831,14491.31,-8742.928,691005.744,780064.087,11462.684,94567.395,554.831,15043.712,10354.28,38665.037,3858452.246
2003.0,1973736.752,275806.323,14424.231,-8535.065,649907.539,763732.695,15600.022,119405.643,534.001,15811.992,11187.466,37529.096,3883185.204
2004.0,1978300.549,268417.308,14810.975,-8488.21,710100.017,788528.387,15252.431,121145.057,575.155,15420.57,14143.741,38116.883,3970555.264
2005.0,2012873.046,270321.255,14691.745,-6557.788,760960.254,781986.365,13464.144,122225.017,550.294,15420.393,17810.549,38856.417,4055422.75
2006.0,1990511.135,289246.416,14568.029,-6557.842,816440.77,787218.636,14176.808,64166.414,507.706,16098.525,26589.137,38762.096,4064702.228
2007.0,2016455.584,247509.974,14637.213,-6896.352,896589.791,806424.753,13453.354,65738.978,611.793,16524.554,34449.927,39014.024,4156744.724
2008.0,1985801.247,254831.385,14839.977,-6288.062,882980.599,806208.435,11706.876,46242.612,864.315,17733.759,55363.1,37299.853,4119387.76
2009.0,1755904.253,273445.094,15008.658,-4627.345,920978.681,798854.585,10632.107,38936.515,891.179,18442.596,73886.132,36050.138,3950330.927
2010.0,1847290.279,260203.069,15219.213,-5501.132,987697.234,806968.301,11312.787,37061.013,1212.182,18917.207,94652.246,37172.16,4125059.9
2011.0,1733430.005,319354.904,15316.068,-6420.516,1013688.929,790204.367,11566.2,30182.245,1817.696,19221.763,120176.599,37449.067,4100140.927
2012.0,1514042.945,276240.223,15562.426,-4950.496,1225894.175,769331.249,11897.585,23189.542,4326.675,19823.037,140821.703,37799.129,4047765.26
2013.0,1581114.716,268565.383,15774.674,-4681.033,1124835.56,789016.473,12852.937,27164.444,9035.62,20830.49,167839.745,40027.537,4065964.068
2014.0,1581710.35,259366.622,15876.941,-6173.548,1126608.958,797165.982,12021.786,30231.862,17691.031,21649.719,181655.282,42339.725,4093606.006
2015.0,1352398.197,249080.085,15917.575,-5091.488,1333482.11,797177.877,13116.698,28248.749,24892.904,21703.372,190718.548,41928.506,4077600.939
2016.0,1239148.654,267812.153,15825.807,-6686.127,1378306.934,805693.948,12807.432,24204.806,36054.121,21813.231,226992.562,40947.227,4076674.984
2017.0,1205835.275,300333.156,15926.765,-6494.548,1296414.692,804949.635,12468.967,21389.958,53286.174,21609.891,254302.662,41151.779,4034268.432
2018.0,1146392.716,291723.816,16728.455,-5904.539,1468012.599,807077.759,12191.182,24571.82,66603.684,21353.868,274951.815,41411.26,4177809.699

In [26]:
# clean up column names

table = table.rename(columns={"Electricity Net Generation From Coal, All Sectors": "Coal",
                     "Electricity Net Generation From Conventional Hydroelectric Power, All Sectors": "Hydroelectric Power",
                     "Electricity Net Generation From Geothermal, All Sectors": "Geothermal",
                     "Electricity Net Generation From Hydroelectric Pumped Storage, All Sectors": "Hydroelectric Pumped Storage",
                     "Electricity Net Generation From Natural Gas, All Sectors": "Natural Gas",
                     "Electricity Net Generation From Nuclear Electric Power, All Sectors": "Nuclear Electric Power",
                     "Electricity Net Generation From Other Gases, All Sectors": "Other Gases",
                     "Electricity Net Generation From Petroleum, All Sectors": "Petroleum",
                     "Electricity Net Generation From Solar, All Sectors": "Solar",
                     "Electricity Net Generation From Waste, All Sectors": "Waste",
                     "Electricity Net Generation From Wind, All Sectors": "Wind",
                     "Electricity Net Generation From Wood, All Sectors": "Wood",
                     "Electricity Net Generation Total (including from sources not shown), All Sectors": "Total"})
table.head()

Description,Coal,Hydroelectric Power,Geothermal,Hydroelectric Pumped Storage,Natural Gas,Nuclear Electric Power,Other Gases,Petroleum,Solar,Waste,Wind,Wood,Total
Year,,,,,,,,,,,,,
1949.0,135451.32,94772.992,Not Available,Not Available,36966.709,0,Not Available,28547.232,Not Available,Not Available,Not Available,386.036,296124.289
1950.0,154519.994,100884.575,Not Available,Not Available,44559.159,0,Not Available,33734.288,Not Available,Not Available,Not Available,389.585,334087.601
1951.0,185203.657,104376.12,Not Available,Not Available,56615.678,0,Not Available,28712.116,Not Available,Not Available,Not Available,390.784,375298.355
1952.0,195436.666,109708.251,Not Available,Not Available,68453.088,0,Not Available,29749.761,Not Available,Not Available,Not Available,481.647,403829.413
1953.0,218846.325,109617.396,Not Available,Not Available,79790.975,0,Not Available,38404.449,Not Available,Not Available,Not Available,389.418,447048.563

In [29]:
table.tail()

Description,Coal,Hydroelectric Power,Geothermal,Hydroelectric Pumped Storage,Natural Gas,Nuclear Electric Power,Other Gases,Petroleum,Solar,Waste,Wind,Wood,Total
Year,,,,,,,,,,,,,
2014.0,1581710.35,259366.622,15876.941,-6173.548,1126608.958,797165.982,12021.786,30231.862,17691.031,21649.719,181655.282,42339.725,4093606.006
2015.0,1352398.197,249080.085,15917.575,-5091.488,1333482.11,797177.877,13116.698,28248.749,24892.904,21703.372,190718.548,41928.506,4077600.939
2016.0,1239148.654,267812.153,15825.807,-6686.127,1378306.934,805693.948,12807.432,24204.806,36054.121,21813.231,226992.562,40947.227,4076674.984
2017.0,1205835.275,300333.156,15926.765,-6494.548,1296414.692,804949.635,12468.967,21389.958,53286.174,21609.891,254302.662,41151.779,4034268.432
2018.0,1146392.716,291723.816,16728.455,-5904.539,1468012.599,807077.759,12191.182,24571.82,66603.684,21353.868,274951.815,41411.26,4177809.699

In [28]:
table.dtypes

Description
Coal                            object
Hydroelectric Power             object
Geothermal                      object
Hydroelectric Pumped Storage    object
Natural Gas                     object
Nuclear Electric Power          object
Other Gases                     object
Petroleum                       object
Solar                           object
Waste                           object
Wind                            object
Wood                            object
Total                           object
dtype: object

# Alternative Topic

## Light-Duty Automotive Technology, Carbon Dioxide Emissions, and Fuel Economy Trends Data

https://catalog.data.gov/dataset/light-duty-automotive-technology-carbon-dioxide-emissions-and-fuel-economy-trends-data-5ff55

https://catalog.data.gov/dataset/fuel-economy-data

- This annual report is part of the U.S. Environmental Protection Agency’s (EPA) commitment to provide the public with information about new light-duty vehicle greenhouse gas (GHG) emissions, fuel economy, technology data, and auto manufacturers' performance in meeting the agency’s GHG emissions standards. 
- EPA has collected data on every new light-duty vehicle model sold in the United States since 1975, either from testing performed by EPA at the National Vehicle and Fuel Emissions Laboratory in Ann Arbor, Michigan, or directly from manufacturers using official EPA test procedures. 
- These data are collected to support several important national programs, including EPA criteria pollutant and GHG standards, the U.S. Department of Transportation’s National Highway Traffic Safety Administration (NHTSA) Corporate Average Fuel Economy (CAFE) standards, and vehicle Fuel Economy and Environment labels.

In [0]:
from google.colab import files
uploaded = files.upload()

In [0]:
vehicles = pd.read_csv(io.BytesIO(uploaded['vehicles.csv']))

vehicles.head()